name: Content
description: Flag missing, incorrect or outdated information
title: ""
labels: ["Content"]
assignees:
  - LukasKrah
body:
  - type: textarea
    id: content-accuracy-details
    attributes:
      label: Content Accuracy Details
      description: Specify the location(s) of the inaccurate information, describe the inaccuracy, and provide the corrected or updated information with supporting evidence.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true